const {test,expect}=require('@playwright/test');const fs=require('fs'),path=require('path');const APP='http://127.0.0.1:4173',EVIDENCE=process.env.ADMIN_FE02C01_EVIDENCE_DIR||'test-evidence/admin-fe02c01';fs.mkdirSync(EVIDENCE,{recursive:true});
const LOCAL_IMAGE='data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 width=%2296%22 height=%22128%22%3E%3Crect width=%2296%22 height=%22128%22 fill=%22%23ddd%22/%3E%3C/svg%3E';const photo=(id,url=LOCAL_IMAGE)=>({publicId:id,url,alt:id});
const product={id:'p1',name:'Sofia',slug:'sofia',description:'',category:'dress',gender:'girls',color:'Bílá',occasion:[],ageTags:[],brand:'',familyLookGroup:'',rentalEnabled:false,saleEnabled:false,defaultDeposit:0,seo:{noIndex:false},photos:[photo('a'),photo('b')],status:'draft',createdAt:'2026-01-01T00:00:00Z',updatedAt:'2026-01-01T00:00:00Z',rentalPrices:{}};
const adminOrigin='http://admin-api.test',productsPath='/api/v2/admin/products';
const matchesAdminProducts=url=>url.origin===adminOrigin&&(url.pathname===productsPath||url.pathname.startsWith(productsPath+'/'));
async function mocks(page,seed=product){await page.addInitScript(()=>localStorage.setItem('persist:auth',JSON.stringify({token:JSON.stringify('admin-test-token')})));await page.route('**/api/users/current',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({user:{_id:'admin-user'}})}));const state={detailHits:0,currentProduct:JSON.parse(JSON.stringify(seed))};await page.route(url=>matchesAdminProducts(url),r=>{const u=new URL(r.request().url());if(u.pathname.endsWith('/admin/products')&&u.searchParams.get('limit')==='1')return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({items:[],pagination:{page:1,limit:1,total:0,pages:0}})});if(r.request().method()==='GET'){state.detailHits++;const body=JSON.stringify({product:state.currentProduct,variants:[]});return r.fulfill({status:200,contentType:'application/json',body})}if(r.request().method()==='DELETE'&&u.pathname.endsWith('/photos')){const body=r.request().postDataJSON();state.currentProduct={...state.currentProduct,photos:state.currentProduct.photos.filter(p=>p.publicId!==body.publicId)};return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({product:state.currentProduct})})}return r.abort('failed')});return state}
test('admin products matcher has exact origin and path boundaries',()=>{expect(matchesAdminProducts(new URL(adminOrigin+productsPath+'?page=1'))).toBe(true);expect(matchesAdminProducts(new URL(adminOrigin+productsPath+'/p1'))).toBe(true);expect(matchesAdminProducts(new URL(adminOrigin+productsPath+'/p1/photos/order'))).toBe(true);expect(matchesAdminProducts(new URL('http://other.test'+productsPath+'/p1'))).toBe(false);expect(matchesAdminProducts(new URL(adminOrigin+productsPath+'-other'))).toBe(false);expect(matchesAdminProducts(new URL(adminOrigin+'/api/v2/admin/reservations'))).toBe(false)});
test('detail request is intercepted as 200 JSON before editor hydration',async({page})=>{const state=await mocks(page);const observed=page.waitForResponse(r=>r.url()===adminOrigin+productsPath+'/p1');await page.goto(APP+'/admin/produkty/p1');const response=await observed;expect(response.request().method()).toBe('GET');expect(response.status()).toBe(200);expect(response.headers()['content-type']).toContain('application/json');expect(await response.json()).toEqual({product,variants:[]});expect(state.detailHits).toBe(1);await expect(page.getByLabel('Název')).toHaveValue('Sofia');await expect(page.getByRole('heading',{name:'Fotografie'})).toBeVisible()});
for(const width of [375,390,430,768,1024,1440])test('media responsive '+width,async({page})=>{await mocks(page);await page.setViewportSize({width,height:1000});await page.goto(APP+'/admin/produkty/p1');await expect(page.getByRole('heading',{name:'Fotografie'})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth-window.innerWidth)).toBeLessThanOrEqual(1);await expect(page.getByText('2 / 10 uložených')).toBeVisible();await expect(page.locator('ol img').first()).toHaveJSProperty('complete',true);await expect(page.locator('ol img').first()).toHaveJSProperty('naturalWidth',96);const form=page.locator('[data-product-core-form]');const fb=await form.boundingBox();const media=page.locator('[data-product-media-section]'),divider=media.locator('hr').first(),heading=page.getByRole('heading',{name:'Fotografie'});const mb=await media.boundingBox(),db=await divider.boundingBox(),hb=await heading.boundingBox();expect(Math.round(db.y-fb.y-fb.height)).toBe(48);expect(Math.round(hb.y-(db.y+db.height))).toBe(32);const geometry={width,media:mb,divider:db,heading:hb,viewport:await page.evaluate(()=>({w:innerWidth,h:innerHeight,scrollWidth:document.documentElement.scrollWidth})),form:fb};fs.writeFileSync(path.join(EVIDENCE,'geometry-'+width+'.json'),JSON.stringify(geometry,null,2));await page.screenshot({path:path.join(EVIDENCE,'responsive-'+width+'.png'),fullPage:true});if(width<768){const item=page.locator('ol > li').first(),remove=page.getByRole('button',{name:'Odebrat fotografii'}).first();const ib=await item.boundingBox(),rb=await remove.boundingBox();expect(rb.y).toBeGreaterThan(ib.y+120);expect(rb.width).toBeGreaterThan(ib.width*0.75)}});
test('dirty order actions keep frozen 16px list rhythm',async({page})=>{await mocks(page);await page.goto(APP+'/admin/produkty/p1');await page.getByRole('button',{name:'Posunout později'}).first().click();const list=page.locator('[data-photo-list]'),actions=page.locator('[data-order-actions]'),lb=await list.boundingBox(),ab=await actions.boundingBox();expect(Math.round(ab.y-(lb.y+lb.height))).toBe(16)});
test('media order makes combined leave risk and can stay',async({page})=>{await mocks(page);await page.goto(APP+'/admin/produkty/p1');await page.getByRole('button',{name:'Posunout později'}).first().click();await page.getByRole('link',{name:'Produkty'}).click();const d=page.getByRole('dialog');await expect(d).toContainText('Neuložené nebo nedokončené změny');await expect(d.getByRole('button',{name:'Zůstat'})).toBeFocused();await d.getByRole('button',{name:'Zůstat'}).click();await expect(page).toHaveURL(/\/admin\/produkty\/p1$/)});

test('short viewport keeps combined dialog actions reachable',async({page})=>{await mocks(page);await page.setViewportSize({width:390,height:360});await page.goto(APP+'/admin/produkty/p1');const move=page.getByRole('button',{name:'Posunout později'}).first();await move.click();const toggle=page.locator('[data-admin-nav-toggle]');await expect(toggle).toHaveAttribute('aria-expanded','false');await toggle.click();await expect(toggle).toHaveAttribute('aria-expanded','true');const mobileNavigation=page.locator('#admin-mobile-navigation');await expect(mobileNavigation).toBeVisible();const productsLink=mobileNavigation.getByRole('link',{name:'Produkty',exact:true});await productsLink.click();const d=page.getByRole('dialog');await expect(d).toContainText('Neuložené nebo nedokončené změny');await expect(page.getByRole('dialog')).toHaveCount(1);await expect(d.getByRole('button',{name:'Zůstat'})).toBeFocused();await expect(d.getByRole('button',{name:'Zůstat'})).toBeVisible();await expect(d.getByRole('button',{name:'Odejít'})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth-window.innerWidth)).toBeLessThanOrEqual(1);await page.screenshot({path:path.join(EVIDENCE,'short-height-dialog-390x360.png')});await d.getByRole('button',{name:'Zůstat'}).click();await expect(d).toBeHidden();await expect(page).toHaveURL(/\/admin\/produkty\/p1$/);await expect(page.getByRole('button',{name:'Uložit pořadí'})).toBeVisible();await expect(toggle).toHaveAttribute('aria-expanded','true');await expect(mobileNavigation).toBeVisible();await expect(productsLink).toBeVisible();await expect(productsLink).toBeFocused()});

test('reorder focus follows same photo at both edges without PATCH',async({page})=>{
 const state=await mocks(page,{...product,photos:[photo('a'),photo('b'),photo('c')]});await page.goto(APP+'/admin/produkty/p1');
 const bRow=page.locator('[data-photo-id="b"]');const later=bRow.getByRole('button',{name:'Posunout později'});await later.focus();await later.click();
 await expect(bRow.getByRole('button',{name:'Posunout dříve'})).toBeFocused();
 await bRow.getByRole('button',{name:'Posunout dříve'}).click();await expect(bRow.getByRole('button',{name:'Posunout dříve'})).toBeFocused();
 expect(state.currentProduct.photos.map(p=>p.publicId)).toEqual(['a','b','c']);
});
test('delete success focuses next surviving photo, then previous at last position',async({page})=>{
 await mocks(page,{...product,photos:[photo('a'),photo('b'),photo('c')]});await page.goto(APP+'/admin/produkty/p1');
 await page.locator('[data-photo-id="b"]').getByRole('button',{name:'Odebrat fotografii'}).click();let d=page.getByRole('dialog');await d.getByRole('button',{name:'Odebrat fotografii'}).click();
 await expect(page.locator('[data-photo-id="c"] [data-media-action]').first()).toBeFocused();
 await page.locator('[data-photo-id="c"]').getByRole('button',{name:'Odebrat fotografii'}).click();d=page.getByRole('dialog');await d.getByRole('button',{name:'Odebrat fotografii'}).click();
 await expect(page.locator('[data-photo-id="a"] [data-media-action]').first()).toBeFocused();
});
test('allowed final-photo delete focuses file trigger and cancel restores delete trigger',async({page})=>{
 await mocks(page,{...product,photos:[photo('a')]});await page.goto(APP+'/admin/produkty/p1');const trigger=page.getByRole('button',{name:'Odebrat fotografii'});
 await trigger.click();let d=page.getByRole('dialog');await d.getByRole('button',{name:'Zrušit'}).click();await expect(trigger).toBeFocused();
 await trigger.click();d=page.getByRole('dialog');await d.getByRole('button',{name:'Odebrat fotografii'}).click();await expect(page.getByRole('button',{name:'Přidat fotografii'})).toBeFocused();await expect(page.getByText('Produkt zatím nemá žádné fotografie.')).toBeVisible();
});
test('broken image uses deliberate fallback while successful image stays loaded',async({page})=>{
 await mocks(page,{...product,photos:[photo('ok'),photo('broken','data:image/png;base64,broken')]});await page.goto(APP+'/admin/produkty/p1');
 await expect(page.locator('[data-photo-id="ok"] img')).toHaveJSProperty('naturalWidth',96);await expect(page.getByText('Náhled fotografie nelze zobrazit')).toBeVisible();
});
