const {test,expect}=require('@playwright/test');const APP='http://127.0.0.1:4173';
const photo=(id)=>({publicId:id,url:'https://example.test/'+id+'.jpg',alt:id});
const product={id:'p1',name:'Sofia',slug:'sofia',description:'',category:'dress',gender:'girls',color:'Bílá',occasion:[],ageTags:[],brand:'',familyLookGroup:'',rentalEnabled:false,saleEnabled:false,defaultDeposit:0,seo:{noIndex:false},photos:[photo('a'),photo('b')],status:'draft',createdAt:'2026-01-01T00:00:00Z',updatedAt:'2026-01-01T00:00:00Z',rentalPrices:{}};
const adminOrigin='http://admin-api.test',productsPath='/api/v2/admin/products';
const matchesAdminProducts=url=>url.origin===adminOrigin&&(url.pathname===productsPath||url.pathname.startsWith(productsPath+'/'));
async function mocks(page){await page.addInitScript(()=>localStorage.setItem('persist:auth',JSON.stringify({token:JSON.stringify('admin-test-token')})));await page.route('**/api/users/current',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({user:{_id:'admin-user'}})}));const state={detailHits:0};await page.route(url=>matchesAdminProducts(url),r=>{const u=new URL(r.request().url());if(u.pathname.endsWith('/admin/products')&&u.searchParams.get('limit')==='1')return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({items:[],pagination:{page:1,limit:1,total:0,pages:0}})});if(r.request().method()==='GET'){state.detailHits++;const body=JSON.stringify({product,variants:[]});return r.fulfill({status:200,contentType:'application/json',body})}return r.abort('failed')});return state}
test('admin products matcher has exact origin and path boundaries',()=>{expect(matchesAdminProducts(new URL(adminOrigin+productsPath+'?page=1'))).toBe(true);expect(matchesAdminProducts(new URL(adminOrigin+productsPath+'/p1'))).toBe(true);expect(matchesAdminProducts(new URL(adminOrigin+productsPath+'/p1/photos/order'))).toBe(true);expect(matchesAdminProducts(new URL('http://other.test'+productsPath+'/p1'))).toBe(false);expect(matchesAdminProducts(new URL(adminOrigin+productsPath+'-other'))).toBe(false);expect(matchesAdminProducts(new URL(adminOrigin+'/api/v2/admin/reservations'))).toBe(false)});
test('detail request is intercepted as 200 JSON before editor hydration',async({page})=>{const state=await mocks(page);const observed=page.waitForResponse(r=>r.url()===adminOrigin+productsPath+'/p1');await page.goto(APP+'/admin/produkty/p1');const response=await observed;expect(response.request().method()).toBe('GET');expect(response.status()).toBe(200);expect(response.headers()['content-type']).toContain('application/json');expect(await response.json()).toEqual({product,variants:[]});expect(state.detailHits).toBe(1);await expect(page.getByLabel('Název')).toHaveValue('Sofia');await expect(page.getByRole('heading',{name:'Fotografie'})).toBeVisible()});
for(const width of [375,390,430,768,1024,1440])test('media responsive '+width,async({page})=>{await mocks(page);await page.setViewportSize({width,height:1000});await page.goto(APP+'/admin/produkty/p1');await expect(page.getByRole('heading',{name:'Fotografie'})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth-window.innerWidth)).toBeLessThanOrEqual(1);await expect(page.getByText('2 / 10 uložených')).toBeVisible();if(width<768){const item=page.locator('ol > li').first(),remove=page.getByRole('button',{name:'Odebrat fotografii'}).first();const ib=await item.boundingBox(),rb=await remove.boundingBox();expect(rb.y).toBeGreaterThan(ib.y+120);expect(rb.width).toBeGreaterThan(ib.width*0.75)}});
test('media order makes combined leave risk and can stay',async({page})=>{await mocks(page);await page.goto(APP+'/admin/produkty/p1');await page.getByRole('button',{name:'Posunout později'}).first().click();await page.getByRole('link',{name:'Produkty'}).click();const d=page.getByRole('dialog');await expect(d).toContainText('Neuložené nebo nedokončené změny');await expect(d.getByRole('button',{name:'Zůstat'})).toBeFocused();await d.getByRole('button',{name:'Zůstat'}).click();await expect(page).toHaveURL(/\/admin\/produkty\/p1$/)});

test('short viewport keeps combined dialog actions reachable',async({page})=>{await mocks(page);await page.setViewportSize({width:390,height:360});await page.goto(APP+'/admin/produkty/p1');await page.getByRole('button',{name:'Posunout později'}).first().click();await page.getByRole('link',{name:'Produkty'}).click();const d=page.getByRole('dialog');await expect(d).toBeVisible();await expect(d.getByRole('button',{name:'Zůstat'})).toBeVisible();await expect(d.getByRole('button',{name:'Odejít'})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth-window.innerWidth)).toBeLessThanOrEqual(1)});
