import type {AdminProduct,AdminProductCategory,AdminProductGender,AdminProductOccasion,CreateAdminProductRequest,UpdateAdminProductRequest} from '../api/products';
export interface ProductCoreFormState{name:string;slug:string;description:string;category:''|AdminProductCategory;gender:''|AdminProductGender;color:string;occasion:AdminProductOccasion[];ageTags:string[];brand:string;familyLookGroup:string;rentalEnabled:boolean;rentalStudioPrice:string;rentalExternalPrice:string;defaultDeposit:string;saleEnabled:boolean;defaultSalePrice:string;seoTitle:string;seoDescription:string}
export const initialProductCoreFormState:ProductCoreFormState={name:'',slug:'',description:'',category:'',gender:'',color:'',occasion:[],ageTags:[],brand:'',familyLookGroup:'',rentalEnabled:false,rentalStudioPrice:'',rentalExternalPrice:'',defaultDeposit:'0',saleEnabled:false,defaultSalePrice:'',seoTitle:'',seoDescription:''};
export const occasionOrder:AdminProductOccasion[]=['wedding','birthday','christening','photoshoot','celebration','other'];
const text=(v?:string)=>v?.trim()??'';
const money=(v:string)=>{const s=v.trim();return /^\d+$/.test(s)?String(Number(s)):s};
export function normalizeCoreFormState(v:ProductCoreFormState):ProductCoreFormState{return {...v,name:text(v.name),slug:text(v.slug),description:text(v.description),color:text(v.color),brand:text(v.brand),familyLookGroup:text(v.familyLookGroup),ageTags:v.ageTags.map(text).filter(Boolean),occasion:[...v.occasion].sort((a,b)=>occasionOrder.indexOf(a)-occasionOrder.indexOf(b)),rentalStudioPrice:v.rentalEnabled?money(v.rentalStudioPrice):'',rentalExternalPrice:v.rentalEnabled?money(v.rentalExternalPrice):'',defaultDeposit:v.rentalEnabled?money(v.defaultDeposit):'',defaultSalePrice:v.saleEnabled?money(v.defaultSalePrice):'',seoTitle:text(v.seoTitle),seoDescription:text(v.seoDescription)}}
export const coreFormStatesEquivalent=(a:ProductCoreFormState,b:ProductCoreFormState)=>JSON.stringify(normalizeCoreFormState(a))===JSON.stringify(normalizeCoreFormState(b));
export function productToCoreFormState(p:AdminProduct):ProductCoreFormState{return {name:p.name??'',slug:p.slug??'',description:p.description??'',category:p.category??'',gender:p.gender??'',color:p.color??'',occasion:p.occasion??[],ageTags:p.ageTags??[],brand:p.brand??'',familyLookGroup:p.familyLookGroup??'',rentalEnabled:Boolean(p.rentalEnabled),rentalStudioPrice:p.rentalPrices?.studio===undefined?'':String(p.rentalPrices.studio),rentalExternalPrice:p.rentalPrices?.external===undefined?'':String(p.rentalPrices.external),defaultDeposit:String(p.defaultDeposit??0),saleEnabled:Boolean(p.saleEnabled),defaultSalePrice:p.defaultSalePrice===undefined?'':String(p.defaultSalePrice),seoTitle:p.seo?.title??'',seoDescription:p.seo?.description??''}}
const num=(s:string)=>Number(s.trim());
export function serializeCreateAdminProduct(state:ProductCoreFormState):CreateAdminProductRequest{const v=normalizeCoreFormState(state);const out:CreateAdminProductRequest={name:v.name};if(v.slug)out.slug=v.slug;if(v.description)out.description=v.description;if(v.category)out.category=v.category;if(v.gender)out.gender=v.gender;if(v.color)out.color=v.color;if(v.occasion.length)out.occasion=v.occasion;if(v.ageTags.length)out.ageTags=v.ageTags;if(v.brand)out.brand=v.brand;if(v.familyLookGroup)out.familyLookGroup=v.familyLookGroup;if(v.rentalEnabled){out.rentalEnabled=true;const rp:any={};if(v.rentalStudioPrice!=='')rp.studio=num(v.rentalStudioPrice);if(v.rentalExternalPrice!=='')rp.external=num(v.rentalExternalPrice);if(Object.keys(rp).length)out.rentalPrices=rp;if(v.defaultDeposit!==''&&num(v.defaultDeposit)!==0)out.defaultDeposit=num(v.defaultDeposit)}if(v.saleEnabled){out.saleEnabled=true;if(v.defaultSalePrice!=='')out.defaultSalePrice=num(v.defaultSalePrice)}if(v.seoTitle||v.seoDescription)out.seo={...(v.seoTitle?{title:v.seoTitle}:{}),...(v.seoDescription?{description:v.seoDescription}:{})};return out}
export function serializeAdminProductPatch(current:ProductCoreFormState,baseline:ProductCoreFormState):UpdateAdminProductRequest{const c=normalizeCoreFormState(current),b=normalizeCoreFormState(baseline),out:UpdateAdminProductRequest={};const simple:(keyof Pick<ProductCoreFormState,'name'|'slug'|'description'|'color'|'brand'|'familyLookGroup'>)[]=['name','slug','description','color','brand','familyLookGroup'];for(const k of simple)if(c[k]!==b[k])(out as any)[k]=c[k];if(c.category!==b.category)out.category=c.category||null;if(c.gender!==b.gender)out.gender=c.gender||null;if(JSON.stringify(c.occasion)!==JSON.stringify(b.occasion))out.occasion=c.occasion;if(JSON.stringify(c.ageTags)!==JSON.stringify(b.ageTags))out.ageTags=c.ageTags;if(c.rentalEnabled!==b.rentalEnabled)out.rentalEnabled=c.rentalEnabled;if(c.rentalEnabled){const rp:NonNullable<UpdateAdminProductRequest['rentalPrices']>={};if(c.rentalStudioPrice!==b.rentalStudioPrice)rp.studio=c.rentalStudioPrice===''?null:num(c.rentalStudioPrice);if(c.rentalExternalPrice!==b.rentalExternalPrice)rp.external=c.rentalExternalPrice===''?null:num(c.rentalExternalPrice);if(Object.keys(rp).length)out.rentalPrices=rp;if(c.defaultDeposit!==b.defaultDeposit)out.defaultDeposit=num(c.defaultDeposit)}if(c.saleEnabled!==b.saleEnabled)out.saleEnabled=c.saleEnabled;if(c.saleEnabled&&c.defaultSalePrice!==b.defaultSalePrice)out.defaultSalePrice=c.defaultSalePrice===''?null:num(c.defaultSalePrice);const seo:any={};if(c.seoTitle!==b.seoTitle)seo.title=c.seoTitle;if(c.seoDescription!==b.seoDescription)seo.description=c.seoDescription;if(Object.keys(seo).length)out.seo=seo;return out}