import {useEffect,useRef,useState} from 'react';
import styled from 'styled-components';
import {Button} from '../../design-system/components/Button';
import {Divider} from '../../design-system/components/Divider';
import {Spinner} from '../../design-system/components/Spinner';
import {StatusBadge} from '../../design-system/components/StatusBadge';
import {designTokens as t} from '../../design-system/tokens/designTokens';
import type {AdminProductPhoto,AdminProductStatus} from '../api/products';
import {useProductMediaController} from './useProductMediaController';

const Section=styled.section`inline-size:100%;max-inline-size:840px;margin-block-start:${t.space[8]};display:grid;gap:${t.space[6]};min-inline-size:0;`;
const HeadingRow=styled.div`margin-block-start:${t.space[2]};display:flex;align-items:baseline;justify-content:space-between;gap:${t.space[3]};@media(max-width:767px){align-items:flex-start;flex-direction:column;}`;
const H2=styled.h2`margin:0;font:600 22px/30px ${t.font.family.ui};`;
const Copy=styled.p`margin:0;color:${t.color.text.secondary};font-size:${t.type.bodySm.size};line-height:${t.type.bodySm.lineHeight};`;
const List=styled.ol`list-style:none;margin:0;padding:0;border:1px solid ${t.color.border.subtle};border-radius:${t.radius[2]};overflow:visible;`;
const Item=styled.li`padding:${t.space[4]};display:grid;grid-template-columns:96px minmax(0,1fr);gap:${t.space[4]};min-inline-size:0;&+&{border-block-start:1px solid ${t.color.border.subtle};}@media(max-width:767px){grid-template-columns:96px minmax(0,1fr);}`;
const Preview=styled.img`inline-size:96px;block-size:128px;object-fit:contain;object-position:center;border-radius:${t.radius[2]};background:${t.color.bg.subtle};`;
const Broken=styled.div`inline-size:96px;block-size:128px;display:grid;place-items:center;text-align:center;border-radius:${t.radius[2]};background:${t.color.bg.subtle};color:${t.color.text.secondary};font-size:12px;`;
const Body=styled.div`min-inline-size:0;display:grid;align-content:start;gap:${t.space[3]};overflow-wrap:anywhere;`;
const Actions=styled.div`display:flex;flex-wrap:wrap;gap:${t.space[2]};@media(max-width:767px){display:grid;grid-template-columns:1fr 1fr;&>[data-wide]{grid-column:1/-1;}}`;
const ItemActions=styled(Actions)`grid-column:1/-1;@media(min-width:768px){grid-column:2;}`;
const AltEditor=styled.div`grid-column:1/-1;display:grid;gap:${t.space[2]};textarea{inline-size:100%;min-block-size:96px;resize:vertical;padding:${t.space[3]};border:1px solid ${t.color.border.default};border-radius:${t.radius[2]};font:inherit;box-sizing:border-box;}`;
const Upload=styled.div`display:grid;gap:${t.space[3]};min-inline-size:0;`;
const Selected=styled.div`display:grid;grid-template-columns:96px minmax(0,1fr);gap:${t.space[4]};align-items:start;overflow-wrap:anywhere;@media(max-width:767px){.selected-actions{grid-column:1/-1;display:grid;gap:${t.space[2]};}}`;
const Progress=styled.progress`inline-size:100%;block-size:8px;accent-color:${t.color.action.primary.bg};`;
const Status=styled.div`min-block-size:20px;color:${t.color.text.secondary};font-size:${t.type.bodySm.size};overflow-wrap:anywhere;`;
const Empty=styled.div`display:grid;gap:${t.space[2]};padding:${t.space[6]};border:1px solid ${t.color.border.subtle};border-radius:${t.radius[2]};`;
const OrderActions=styled(Actions)`margin-block-start:-${t.space[2]};@media(max-width:767px){display:grid;grid-template-columns:1fr;}`;
const phaseCopy:Record<string,string>={selected:'Fotografie je připravena k nahrání.',signing:'Připravujeme bezpečné nahrání fotografie…',uploading:'Fotografie se nahrává…',completing:'Ověřujeme připojení fotografie k produktu…',unknown:'Výsledek nahrání se nepodařilo potvrdit.', 'provider-confirmed-unattached':'Připojení fotografie není potvrzené','identity-mismatch':'Nahraná fotografie neodpovídá podepsanému identifikátoru. Připojení je zablokované.'};
export interface ProductMediaSectionProps{productId:string;productName:string;status?:AdminProductStatus;token:string;initialPhotos:AdminProductPhoto[];onRiskChange?(risk:boolean):void;onProductMissing?():void;onAccessError?(error:unknown):boolean;onRequestDelete?(input:{publicId:string;trigger:HTMLElement;distinctCount:number;isMain:boolean}):void;deleteRequest?:{publicId:string;nonce:number}|null;onDeleteSettled?(input:{publicId:string;success:boolean;focusTarget?:HTMLElement|null}):void}
export function ProductMediaSection(props:ProductMediaSectionProps){
 const c=useProductMediaController(props),inputRef=useRef<HTMLInputElement>(null),sectionRef=useRef<HTMLElement>(null),[broken,setBroken]=useState<Record<string,boolean>>({});
 const ordered=c.drafts.orderIds.map(id=>c.photos.find(p=>p.publicId===id)).filter(Boolean) as AdminProductPhoto[];
 const busy=Boolean(c.operation),disabled=c.guard!=='available'||busy;
 const selectedPreview=c.attempt?.previewUrl;
 const handledDelete=useRef(0),deleteRequest=props.deleteRequest,onDeleteSettled=props.onDeleteSettled,removePhoto=c.remove;
 useEffect(()=>{const request=deleteRequest;if(!request||request.nonce===handledDelete.current)return;handledDelete.current=request.nonce;const before=c.drafts.orderIds;const removedIndex=before.indexOf(request.publicId);void removePhoto(request.publicId).then(success=>requestAnimationFrame(()=>{let focusTarget:HTMLElement|null=null;if(success){const remaining=before.filter(id=>id!==request.publicId);const nextId=remaining[Math.min(removedIndex,remaining.length-1)];if(nextId)focusTarget=sectionRef.current?.querySelector<HTMLElement>(`[data-photo-id="${nextId}"] [data-media-action]:not(:disabled)`)??null;focusTarget??=sectionRef.current?.querySelector<HTMLElement>('[data-photo-file-trigger]:not(:disabled)')??null;focusTarget??=sectionRef.current?.querySelector<HTMLElement>('#product-media-title')??null}onDeleteSettled?.({publicId:request.publicId,success,focusTarget})}))},[deleteRequest,onDeleteSettled,removePhoto]);
 return <Section ref={sectionRef} aria-labelledby="product-media-title"><Divider/><HeadingRow><H2 id="product-media-title" tabIndex={-1}>Fotografie</H2><Copy>{c.photos.length} / 10 uložených</Copy></HeadingRow><Copy>Spravujte fotografie produktu a jejich pořadí. První fotografie se používá jako hlavní.</Copy>
  <Upload><input ref={inputRef} type="file" accept="image/jpeg,image/png,image/webp" hidden onChange={e=>{const f=e.currentTarget.files?.[0];if(f)c.selectFile(f);e.currentTarget.value=''}} aria-describedby="product-media-file-help"/><Button data-photo-file-trigger disabled={disabled||c.photos.length>=10||c.uploadPhase!=='idle'} onClick={()=>inputRef.current?.click()}>Přidat fotografii</Button><Copy id="product-media-file-help">JPG, JPEG, PNG nebo WEBP, maximálně 15 MB.</Copy>
  {c.photos.length>=10?<Status>Produkt může mít maximálně 10 fotografií.</Status>:null}
  {c.attempt?<Selected>{selectedPreview?<Preview src={selectedPreview} alt="Náhled vybrané fotografie"/>:null}<div><strong>{c.attempt.filename}</strong><Copy>{phaseCopy[c.uploadPhase]??''}</Copy></div><div className="selected-actions">{c.uploadPhase==='selected'?<Button disabled={busy} onClick={c.upload}>Nahrát fotografii</Button>:null}{c.uploadPhase==='unknown'?<Button disabled={busy||!c.attempt.candidate} onClick={c.recover}>Ověřit a připojit</Button>:null}{c.uploadPhase==='provider-confirmed-unattached'?<Button disabled={busy||!c.attempt.providerPublicId} onClick={c.recover}>Zkusit připojit znovu</Button>:null}<Button variant="secondary" disabled={busy} onClick={c.discardUpload}>Zrušit</Button></div>{c.uploadPhase==='uploading'?<div style={{gridColumn:'1/-1'}}><Progress max={100} {...(c.progress===null?{}:{value:c.progress})}/><Copy>{c.progress===null?'Nahrávání…':`${c.progress} %`}</Copy></div>:null}{c.uploadPhase==='signing'||c.uploadPhase==='completing'?<Spinner size="sm"/>:null}</Selected>:null}
  </Upload>
  {c.photos.length===0?<Empty><strong>Produkt zatím nemá žádné fotografie.</strong><Copy>Přidejte první fotografii. Po připojení se automaticky stane hlavní fotografií produktu.</Copy></Empty>:<List>{ordered.map((photo,index)=><Item key={photo.publicId} data-photo-id={photo.publicId}>{broken[photo.publicId]?<Broken>Náhled fotografie nelze zobrazit</Broken>:<Preview src={photo.url} alt={photo.alt||props.productName} onError={()=>setBroken(x=>({...x,[photo.publicId]:true}))}/>}<Body>{index===0?<StatusBadge tone="neutral" style={{justifySelf:'start'}}>Hlavní fotografie</StatusBadge>:null}<div><strong>Alternativní text</strong><Copy>{photo.alt||props.productName}</Copy></div></Body><ItemActions><Button data-media-action="edit" data-wide size="compact" variant="secondary" disabled={disabled||Boolean(c.editingAlt&&c.editingAlt!==photo.publicId)} onClick={()=>c.startAlt(photo.publicId)}>Upravit ALT</Button><Button data-media-action="delete" data-wide size="compact" variant="destructive" disabled={disabled} onClick={e=>props.onRequestDelete?.({publicId:photo.publicId,trigger:e.currentTarget,distinctCount:new Set(c.photos.map(p=>p.publicId)).size,isMain:index===0})}>Odebrat fotografii</Button><Button data-media-action="earlier" size="compact" variant="secondary" disabled={disabled||index===0} onClick={e=>{c.move(photo.publicId,-1);requestAnimationFrame(()=>{const row=sectionRef.current?.querySelector<HTMLElement>(`[data-photo-id="${photo.publicId}"]`);const same=row?.querySelector<HTMLElement>('[data-media-action="earlier"]:not(:disabled)');const opposite=row?.querySelector<HTMLElement>('[data-media-action="later"]:not(:disabled)');(same??opposite??row?.querySelector<HTMLElement>('[data-media-action]:not(:disabled)'))?.focus()})}}>Posunout dříve</Button><Button data-media-action="later" size="compact" variant="secondary" disabled={disabled||index===ordered.length-1} onClick={e=>{c.move(photo.publicId,1);requestAnimationFrame(()=>{const row=sectionRef.current?.querySelector<HTMLElement>(`[data-photo-id="${photo.publicId}"]`);const same=row?.querySelector<HTMLElement>('[data-media-action="later"]:not(:disabled)');const opposite=row?.querySelector<HTMLElement>('[data-media-action="earlier"]:not(:disabled)');(same??opposite??row?.querySelector<HTMLElement>('[data-media-action]:not(:disabled)'))?.focus()})}}>Posunout později</Button></ItemActions>{c.editingAlt===photo.publicId?<AltEditor><label htmlFor={`alt-${photo.publicId}`}><strong>Alternativní text</strong></label><textarea id={`alt-${photo.publicId}`} maxLength={180} value={c.drafts.altById[photo.publicId]??''} onChange={e=>c.setDrafts(d=>({...d,altById:{...d.altById,[photo.publicId]:e.target.value}}))}/><Actions><Button disabled={busy} onClick={c.saveAlt}>Uložit ALT</Button><Button variant="secondary" disabled={busy} onClick={c.cancelAlt}>Zrušit</Button></Actions></AltEditor>:null}</Item>)}</List>}
  {c.orderDirty?<OrderActions><Button disabled={busy} onClick={c.saveOrder}>Uložit pořadí</Button><Button variant="secondary" disabled={busy} onClick={c.cancelOrder}>Zrušit změny pořadí</Button></OrderActions>:null}
  {c.lostAltNotice!==null?<Empty><strong>Rozpracovaný ALT text</strong><Copy>{c.lostAltNotice||'Prázdný ALT text'}</Copy></Empty>:null}{c.guard==='product-missing'?<Empty><strong>Produkt už není dostupný</strong><Copy>Produkt už nebyl nalezen. Další změny fotografií nelze uložit.</Copy><Copy>Vaše neuložené změny na této stránce zůstávají zachované, dokud ji neopustíte.</Copy></Empty>:null}{c.refreshReason?<Button variant="secondary" disabled={busy} onClick={c.refresh}>Načíst aktuální fotografie</Button>:null}<Status role="status" aria-live="polite" aria-atomic="true">{c.uploadPhase!=='uploading'&&c.uploadPhase!=='idle'?(phaseCopy[c.uploadPhase]??c.feedback):c.feedback}</Status>
  
 </Section>
}
