import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {getAdminProductDetail,type AdminProduct,type AdminProductPhoto,type AdminProductStatus} from '../api/products';
import {completeProductPhoto,deleteProductPhoto,productMediaCandidate,reorderProductPhotos,signProductPhoto,updateProductPhotoAlt,type ProductMediaUploadDescriptor} from '../api/productMedia';
import {AdminApiError} from '../api/errors';
import {uploadProductMedia,ProviderUploadError} from '../media/productMediaProviderTransport';
import {distinctPhotoIds,isOrderDirty,moveId,photoIds,reconcileMediaDrafts,validateAlt,validatePhotoFile,type MediaGuardStatus,type ProductMediaDrafts} from './productMediaModel';

type UploadPhase='idle'|'selected'|'signing'|'uploading'|'provider-confirmed'|'completing'|'unknown'|'provider-confirmed-unattached';
interface Attempt{attemptId:number;productId:string;file:File;filename:string;previewUrl:string;descriptor?:ProductMediaUploadDescriptor;candidate?:string;providerPublicId?:string}
export function useProductMediaController(input:{productId:string;productName:string;status?:AdminProductStatus;token:string;initialPhotos:AdminProductPhoto[];onRiskChange?(risk:boolean):void;onProductMissing?():void}){
 const [photos,setPhotos]=useState(input.initialPhotos),[guard,setGuard]=useState<MediaGuardStatus>('available'),[drafts,setDrafts]=useState<ProductMediaDrafts>({altById:{},orderIds:photoIds(input.initialPhotos)});
 const [operation,setOperation]=useState<string|null>(null),[feedback,setFeedback]=useState<string|null>(null),[uploadPhase,setUploadPhase]=useState<UploadPhase>('idle'),[progress,setProgress]=useState<number|null>(null),[attempt,setAttempt]=useState<Attempt|null>(null),[editingAlt,setEditingAlt]=useState<string|null>(null);
 const writeGen=useRef(0),refreshGen=useRef(0),attemptSeq=useRef(0),mounted=useRef(true),controller=useRef<AbortController|null>(null),refreshController=useRef<AbortController|null>(null),productRef=useRef(input.productId);
 useEffect(()=>{mounted.current=true;productRef.current=input.productId;return()=>{mounted.current=false;writeGen.current++;refreshGen.current++;controller.current?.abort();refreshController.current?.abort()}},[input.productId]);
 useEffect(()=>()=>{if(attempt?.previewUrl)URL.revokeObjectURL(attempt.previewUrl)},[attempt?.previewUrl]);
 useEffect(()=>{setPhotos(input.initialPhotos);setDrafts(d=>reconcileMediaDrafts({previousPhotos:photos,previousDrafts:d,nextPhotos:input.initialPhotos}).drafts)},[input.initialPhotos]);
 const orderDirty=isOrderDirty(photos,drafts.orderIds),altDirty=editingAlt?((drafts.altById[editingAlt]??photos.find(p=>p.publicId===editingAlt)?.alt??'')!==(photos.find(p=>p.publicId===editingAlt)?.alt??'')):false;
 const risk=Boolean(operation||uploadPhase!=='idle'||orderDirty||altDirty);useEffect(()=>input.onRiskChange?.(risk),[risk,input.onRiskChange]);
 const safe=(g:number)=>mounted.current&&productRef.current===input.productId&&g===writeGen.current;
 const apply=(product:AdminProduct)=>{setPhotos(product.photos);setDrafts(d=>reconcileMediaDrafts({previousPhotos:photos,previousDrafts:d,nextPhotos:product.photos}).drafts);setGuard('available')};
 const fail=(e:unknown,g:number,defaultCopy:string)=>{if(!safe(g))return;if(e instanceof AdminApiError&&e.code==='PHOTO_NOT_FOUND'){setFeedback('Fotografie už u produktu není. Načtěte aktuální fotografie.');return}if(e instanceof AdminApiError&&(e.code==='PRODUCT_NOT_FOUND'||(e.status===404&&e.code!=='PHOTO_NOT_FOUND'))){setGuard('product-missing');input.onProductMissing?.();setFeedback('Produkt už nebyl nalezen. Další změny fotografií nelze uložit.');return}if(e instanceof AdminApiError&&e.code==='MEDIA_CONFIGURATION_ERROR'){setGuard('configuration-error');setFeedback('Služba fotografií není správně nakonfigurovaná.');return}setFeedback(defaultCopy)};
 const begin=(name:string)=>{const g=++writeGen.current;refreshGen.current++;controller.current?.abort();controller.current=new AbortController();setOperation(name);setFeedback(null);return {g,signal:controller.current.signal}};
 const finish=(g:number)=>{if(safe(g)){setOperation(null);setProgress(null)}};
 const selectFile=useCallback((file:File)=>{const error=validatePhotoFile(file);if(error){setFeedback(error);return}if(photos.length>=10){setFeedback('Produkt může mít maximálně 10 fotografií.');return}if(attempt?.previewUrl)URL.revokeObjectURL(attempt.previewUrl);const previewUrl=URL.createObjectURL(file);setAttempt({attemptId:++attemptSeq.current,productId:input.productId,file,filename:file.name,previewUrl});setUploadPhase('selected');setFeedback(null)},[photos.length,attempt,input.productId]);
 const discardUpload=()=>{if(attempt?.previewUrl)URL.revokeObjectURL(attempt.previewUrl);setAttempt(null);setUploadPhase('idle');setProgress(null)};
 const upload=async()=>{if(!attempt||guard!=='available'||operation)return;const {g,signal}=begin('upload');let providerSucceeded=false;try{setUploadPhase('signing');const signed=await signProductPhoto({token:input.token,productId:input.productId,signal});if(!safe(g))return;const descriptor=signed.upload,candidate=productMediaCandidate(descriptor);setAttempt(a=>a?{...a,descriptor,candidate}:a);setUploadPhase('uploading');const provider=await uploadProductMedia({upload:descriptor,file:attempt.file,signal,onProgress:v=>safe(g)&&setProgress(v)});providerSucceeded=true;if(!safe(g))return;setAttempt(a=>a?{...a,providerPublicId:provider.publicId}:a);setUploadPhase('provider-confirmed');setProgress(null);setUploadPhase('completing');const completed=await completeProductPhoto({token:input.token,productId:input.productId,publicId:provider.publicId,signal});if(!safe(g))return;apply(completed.product);setFeedback('Fotografie byla připojena k produktu.');discardUpload()}catch(e){if(!safe(g)||((e as any)?.name==='AbortError'))return;if(e instanceof ProviderUploadError&&e.outcome==='unknown'){setUploadPhase('unknown');setFeedback('Fotografie mohla být nahrána. Zatím ji znovu nenahrávejte.')}else if(providerSucceeded){setUploadPhase('provider-confirmed-unattached');setFeedback('Fotografie byla nahrána, ale její připojení k produktu se nepodařilo potvrdit.')}else{setUploadPhase('selected');fail(e,g,'Fotografii se nepodařilo nahrát.')}}finally{finish(g)}};
 const recover=async()=>{if(!attempt||operation)return;const id=attempt.providerPublicId??attempt.candidate;if(!id){setFeedback('Výsledek nahrání se nepodařilo potvrdit.');return}const {g,signal}=begin('recover');try{setUploadPhase('completing');const result=await completeProductPhoto({token:input.token,productId:input.productId,publicId:id,signal});if(!safe(g))return;const attached=result.product.photos.some(p=>p.publicId===id);apply(result.product);if(attached){setFeedback('Fotografie byla připojena k produktu.');discardUpload()}else{setUploadPhase('unknown');setFeedback('Výsledek se stále nepodařilo ověřit')}}catch(e){if(!safe(g))return;if(e instanceof AdminApiError&&e.status===502&&e.code==='CLOUDINARY_OPERATION_FAILED'){setUploadPhase('unknown');setFeedback('Služba fotografie nepotvrdila, zda soubor existuje. Fotografie zatím není potvrzeně připojena k produktu.')}else fail(e,g,'Výsledek se stále nepodařilo ověřit')}finally{finish(g)}};
 const refresh=async()=>{if(operation)return;const g=++refreshGen.current;const observedWrite=writeGen.current;refreshController.current?.abort();const ac=new AbortController();refreshController.current=ac;setFeedback(null);try{const r=await getAdminProductDetail({token:input.token,productId:input.productId,signal:ac.signal});if(!mounted.current||productRef.current!==input.productId||g!==refreshGen.current||observedWrite!==writeGen.current)return;apply(r.product);setFeedback('Aktuální fotografie byly načteny.')}catch(e){if(!mounted.current||g!==refreshGen.current)return;fail(e,writeGen.current,'Fotografie se nepodařilo znovu načíst.')}finally{if(g===refreshGen.current)refreshController.current=null}};
 const startAlt=(id:string)=>{setEditingAlt(id);setDrafts(d=>({...d,altById:{...d.altById,[id]:photos.find(p=>p.publicId===id)?.alt??''}}))};
 const cancelAlt=()=>{if(editingAlt)setDrafts(d=>{const x={...d.altById};delete x[editingAlt];return {...d,altById:x}});setEditingAlt(null)};
 const saveAlt=async()=>{if(!editingAlt||operation)return;const value=drafts.altById[editingAlt]??'',error=validateAlt(value);if(error){setFeedback(error);return}const id=editingAlt,{g,signal}=begin('alt');try{const r=await updateProductPhotoAlt({token:input.token,productId:input.productId,publicId:id,alt:value,signal});if(!safe(g))return;apply(r.product);setEditingAlt(null);setFeedback('Alternativní text byl uložen.')}catch(e){fail(e,g,'Alternativní text se nepodařilo uložit.')}finally{finish(g)}};
 const move=(id:string,delta:-1|1)=>setDrafts(d=>({...d,orderIds:moveId(d.orderIds,id,delta)}));
 const cancelOrder=()=>setDrafts(d=>({...d,orderIds:photoIds(photos)}));
 const saveOrder=async()=>{if(!orderDirty||operation)return;const {g,signal}=begin('order');try{const r=await reorderProductPhotos({token:input.token,productId:input.productId,publicIds:drafts.orderIds,signal});if(!safe(g))return;apply(r.product);setFeedback('Pořadí fotografií bylo uloženo.')}catch(e){if(e instanceof AdminApiError&&e.status===409&&e.code==='PHOTO_STATE_CONFLICT')setFeedback('Fotografie se mezitím změnily jinde. Načtěte aktuální stav a zkontrolujte své změny.');else fail(e,g,'Pořadí fotografií se nepodařilo uložit.')}finally{finish(g)}};
 const remove=async(id:string)=>{if(operation)return;const distinct=distinctPhotoIds(photos);if(input.status==='active'&&distinct.length===1){setFeedback('Aktivní produkt musí mít alespoň jednu fotografii.');return}const {g,signal}=begin('delete');try{const r=await deleteProductPhoto({token:input.token,productId:input.productId,publicId:id,signal});if(!safe(g))return;apply(r.product);setFeedback('Fotografie byla odebrána z produktu.')}catch(e){fail(e,g,'Fotografii se nepodařilo odebrat.')}finally{finish(g)}};
 return {photos,guard,drafts,setDrafts,operation,feedback,uploadPhase,progress,attempt,editingAlt,orderDirty,risk,selectFile,discardUpload,upload,recover,startAlt,cancelAlt,saveAlt,move,cancelOrder,saveOrder,remove,refresh};
}
